# Generated by Django 2.0.2 on 2018-03-17 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('minimumparticipant', models.PositiveIntegerField()),
                ('maximumparticipant', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=20)),
                ('entries', models.PositiveIntegerField()),
                ('fees', models.PositiveIntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sponser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('contact', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
