# Generated by Django 2.0.2 on 2018-03-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20180317_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponser',
            name='positive',
            field=models.IntegerField(default=1),
        ),
    ]
