# Generated by Django 2.0.2 on 2018-03-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20180318_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
